import Navbar from "@/components/Navbar";
import "./globals.css";
import { Public_Sans } from 'next/font/google';
import Footer from "@/components/Footer";

export const metadata = {
  title: "Frontend Mentor | Easybank landing page",
  description: "Generated by create next app",
};

export const publicSans = Public_Sans({weight : "300", preload : false})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" type="image/png" sizes="32x32" href="./images/favicon-32x32.png" />
      <body className={publicSans.className}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
