import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Frontend Mentor | Easybank landing page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" type="image/png" sizes="32x32" href="./images/favicon-32x32.png" />
      <body>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
